{
    'name': 'Car Lease',
    'version': '1.0.0',
    'category': 'Transportation',
    'sequence': -100,
    'summary': 'Car Leasing Application',
    'description': """Car Leasing Application""",
    'depends': ['mail'],
    'data': [
        'security\ir.model.access.csv',
        'views/customer_view.xml',
        'views/car_view.xml',
        'views/appointment_view.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'assets': {},
    'license': 'LGPL-3',
}
